version: '2'
services:
  odk:
    build: odk
    container_name: odk
    tty: true
    environment:
      - ODK_HOSTNAME
      - ODK_ADMIN_USERNAME=ops
      - DB_USER
      - DB_DATABASE
      - DB_SCHEMA
      - DB_PASSWORD
      - DB_HOSTNAME
      - PGPASSWORD
      - ODK_INSTANCE_ID
    restart: always
  nginx:
    build: nginx
    environment:
      - SSL_CERTIFICATE
      - SSL_CERTIFICATE_KEY
    ports:
      - 80:80
      - 443:443
    depends_on:
      - odk
    volumes:
      - "/etc/letsencrypt/:/etc/letsencrypt"

    hostname: nginx
    command: /bin/run.sh
    restart: always
