version: '2'
services:
  odk:
    build: odk
    container_name: odk
    tty: true
    environment:
      - ODK_HOSTNAME
      - ODK_ADMIN_USERNAME=ops
      - ODK_PORT=80
      - ODK_PORT_SECURE=443
      - DB_USER=odk_user
      - DB_DATABASE=odk_db
      - DB_SCHEMA=odk_db
      - DB_PASSWORD
      - DB_HOSTNAME
      - PGPASSWORD
      - ODK_INSTANCE_ID
      - DB_LIFETIME=100000 # ms
    restart: always
  nginx:
    build: nginx
    environment:
      - SSL_CERTIFICATE
      - SSL_CERTIFICATE_KEY
    ports:
      - 80:80
      - 443:443
    depends_on:
      - odk
    volumes:
      - "./config:/etc/nginx/config"
      - "/etc/letsencrypt:/etc/letsencrypt"

    hostname: nginx
    command: /bin/run.sh
    restart: always
