version: '2'
services:
  odk:
    build: odk
    container_name: odk
    tty: true
    environment:
      - ODK_HOSTNAME
      - ODK_PORT
      - ODK_PORT_SECURE
      - ODK_ADMIN_USERNAME
      - DB_USER
      - DB_DATABASE
      - DB_SCHEMA
      - DB_PASSWORD
      - DB_HOSTNAME
      - PGPASSWORD
      - ODK_INSTANCE_ID
      - DB_LIFETIME=100000 # ms
      - ODK_AUTH_REALM
      - CATALINA_OPTS=-Xms2g -Xmx3584M -XX:MaxPermSize=512M
    restart: always

  nest:
    build: nest
    volumes:
      - "../meerkat_nest/:/var/www/meerkat_nest"
      - "~/.aws/:/root/.aws"
    environment:
      - "CONFIG_OBJECT=config.Development"
      - MEERKAT_NEST_DB_URL
    hostname: nest
    restart: always

  drill:
    build: drill
    volumes:
      - "../meerkat_drill/:/var/www/meerkat_drill"
      - "~/.aws/:/root/.aws"
    restart: always
  redis:
    image: redis:3.2.11
    hostname: redis
    restart: always

  nginx:
    build: nginx
    environment:
      - SSL_CERTIFICATE
      - SSL_CERTIFICATE_KEY
    volumes:
      - "./nginx/config:/etc/nginx"
      - "/etc/letsencrypt:/etc/letsencrypt"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - odk
      - nest
    hostname: nginx
    command: /bin/run.sh
    restart: always
