
version: '2'
services:
  odk:
    build: odk
    container_name: odk
    tty: true
    environment:
      - ODK_HOSTNAME=localhost
      - ODK_ADMIN_USERNAME=test
      - ODK_PORT=80
      - ODK_PORT_SECURE=443
      - DB_USER=odk_user
      - DB_DATABASE=odk_db
      - DB_SCHEMA=odk_db
      - DB_PASSWORD=password
      - DB_HOSTNAME=db
      - PGPASSWORD=password
      - ODK_INSTANCE_ID=meerkat_odk
      - DB_LIFETIME=100000 # ms
      - CATALINA_OPTS=-Xms2g -Xmx3584M -XX:MaxPermSize=512M
    restart: always


  nest:
    build: nest
    volumes:
      - "../meerkat_nest/:/var/www/meerkat_nest"
      - "~/.aws/:/root/.aws"
    environment:
      - "CONFIG_OBJECT=config.Development"
      - "MEERKAT_NEST_DB_URL=postgresql+psycopg2://postgres:password@db/meerkat_nest_db"
    hostname: nest
    restart: always

  drill:
    build: drill
    volumes:
      - "../meerkat_drill/:/var/www/meerkat_drill"
      - "~/.aws/:/root/.aws"
    restart: always
  redis:
    image: redis:3.2.11
    hostname: redis
    restart: always

  nginx:
    build: nginx
    environment:
      - "SSL_CERTIFICATE=/etc/nginx/self-signed-nginx.crt"
      - "SSL_CERTIFICATE_KEY=/etc/nginx/self-signed-nginx.key"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - odk
      - nest
    hostname: nest_nginx
    command: /bin/run.sh
    restart: always
volumes:
  database_volume:
