version: '2'
services:
  odk:
    build: odk
    container_name: odk
    tty: true
    depends_on:
      - nest_db
    links:
      - nest_db
    environment:
      - ODK_HOSTNAME=localhost
      - ODK_ADMIN_USERNAME=test
      - ODK_PORT=80
      - ODK_PORT_SECURE=443
      - DB_USER=odk_user
      - DB_DATABASE=odk_db
      - DB_SCHEMA=odk_db
      - DB_PASSWORD=password
      - DB_HOSTNAME=nest_db
      - PGPASSWORD=password
      - ODK_CHANNELTYPE=REQUIRES_INSECURE_CHANNEL

  nest_db:
    build:
      context: .
      dockerfile: db/Dockerfile
    hostname:
      nest_db
    volumes:
      - database_volume:/var/lib/postgresql/
      - ./db/postgresql.conf:/etc/postgresql.conf
      - /etc/wal-e.d/env/:/etc/wal-e.d/env/
      - /etc/wal-e.d/gpg_pub.key:/etc/wal-e.d/gpg_pub.key
      - ./db/init_odk_database.sql:/docker-entrypoint-initdb.d/init_odk_database.sql
      #- ./db/configure_backup.sh:/docker-entrypoint-initdb.d/configure_backup.sh
      - ./db/trust_gpg.exp:/usr/bin/trust_gpg.exp
      - ./db/manual_setup.sh:/manual_setup.sh
    environment:
      - POSTGRES_PASSWORD=password
    command: postgres -c config_file=/etc/postgresql.conf

  nest:
    build: nest
    volumes:
      - "../meerkat_nest/:/var/www/meerkat_nest"
      - "~/.aws/:/root/.aws"
    environment:
      - "CONFIG_OBJECT=config.Development"
      - "MEERKAT_NEST_DB_URL=postgresql+psycopg2://postgres:password@nest_db/meerkat_nest_db"
    hostname: nest

  nest_rabbit:
    image: rabbitmq
    hostname: nest_rabbit

  drill:
    build: drill
    volumes:
      - "../meerkat_drill/:/var/www/meerkat_drill"
      - "~/.aws/:/root/.aws"

  redis:
    image: redis:3.2.11
    hostname: redis

  tunnel:
     image: vsouza/sqs-local
     hostname: tunnel
     ports:
      - 9324:9324

  nest_nginx:
    build: nginx
    environment:
      - "SSL_CERTIFICATE=/etc/nginx/self-signed-nginx.crt"
      - "SSL_CERTIFICATE_KEY=/etc/nginx/self-signed-nginx.key"
    depends_on:
      - odk
      - nest
    hostname: nest_nginx
    command: /bin/run.sh
volumes:
  database_volume:
