version: '2'
services:
  odk:
    depends_on:
      - db
    links:
      - db
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    hostname:
      db
    volumes:
      - database_volume:/var/lib/postgresql/
      - ./db/postgresql.conf:/etc/postgresql.conf
      - ./db/init_odk_database.sql:/docker-entrypoint-initdb.d/init_odk_database.sql
    environment:
      - POSTGRES_PASSWORD=password
    command: postgres -c config_file=/etc/postgresql.conf
    restart: always
volumes:
  database_volume: